# Generated by Django 4.2.5 on 2023-10-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/sample.jpg', null=True, upload_to='static/images'),
        ),
    ]
